releases:
  - name: ingress
    namespace: ingress-controller
    chart: ../Helm_Ingress/nginx-ingress
    values:
      - ../Helm_Ingress/nginx-ingress/values.yaml

  - name: cert-manager
    namespace: certmanager
    chart: ../Helm_Cert-manager
    values:
      - ../Helm_Cert-manager/values.yaml

  - name: mariadb
    namespace: wordpressmariadb
    chart: ../Helm_Mariadb
    values:
      - ../Helm_Mariadb/values.yaml

  - name: maxscale
    namespace: wordpressmariadb
    chart: ../Helm_Maxscale
    values:
      - ../Helm_Maxscale/values.yaml

  - name: wordpress
    namespace: wordpressmariadb
    chart: ../Helm_Wordpress
    values:
      - ../Helm_Wordpress/values.yaml
