releases:
  # Ingress Controller
  - name: ingress
    namespace: ingress-controller
    chart: ../Helm_Ingress/nginx-ingress
    values:
      - ../Charts/Helm_Ingress/nginx-ingress/values.yaml

  # Cert Manager
  - name: cert-manager
    namespace: certmanager
    chart: ../Helm_Cert-manager
    values:
      - ../Charts/Helm_Cert-manager/values.yaml

  # MariaDB
  - name: mariadb
    namespace: wordpressmariadb
    chart: ../Helm_Mariadb
    values:
      - ../Charts/Helm_Mariadb/values.yaml

  # Wordpress
  - name: wordpress
    namespace: wordpressmariadb
    chart: ../Helm_Wordpress
    values:
      - ../Charts/Helm_Wordpress/values.yaml

  # Maxscale
  - name: maxscale
    namespace: wordpressmariadb
    chart: ../Charts/Helm_Maxscale
    values:
      - ../Charts/Helm_Maxscale/values.yaml