releases:
  # Ingress Controller
  - name: ingress
    namespace: ingress-controller
    chart: ../Helm_Ingress/nginx-ingress
    values:
      - ../Helm_Ingress/nginx-ingress/values.yaml

  # Cert Manager
  - name: cert-manager
    namespace: certmanager
    chart: ../Helm_Cert-manager
    values:
      - ../Helm_Cert-manager/values.yaml

  # MariaDB
  - name: mariadb
    namespace: wordpressmariadb
    chart: ../Helm_Mariadb
    values:
      - ../Helm_Mariadb/values.yaml

  # Wordpress
  - name: wordpress
    namespace: wordpressmariadb
    chart: ../Helm_Wordpress
    values:
      - ../Helm_Wordpress/values.yaml