apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.mariadb.mariadb_secret_name }}
    namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Encoded value: echo -n 'secret'|base64
  mariadb-root-password: cm9vdHBhc3N3b3Jk #rootpassword
  mysql_user: d29yZHByZXNz #wordpress
  mysql_password: d29yZHByZXNzcGFzc3dvcmQ= #wordpresspassword

