apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: wordpressmariadb
data:
  my.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
    explicit_defaults_for_timestamp
