apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpressmariadb
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        webserver: nginx  # Add this line
    spec:
      containers:
      - name: wordpress
        image: wordpress:php8.2-fpm
        env:

        - name: WORDPRESS_DB_HOST
          value: "mariadb:3306"

        - name: WORDPRESS_DB_PASSWORD
          value: wordpresspassword

        - name: WORDPRESS_DB_NAME
          value: wordpress

        - name: WORDPRESS_DB_USER
          value: wordpress

        ports:
        - containerPort: 9000
        volumeMounts:                      # Add this section
        - name: shared-data
          mountPath: /var/www/
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:                      # Add this section
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
        - name: shared-data
          mountPath: /var/www/
      volumes:                                       # Add this section
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: shared-data
        hostPath:
          # directory location on host
          path: /path-on-host-machine
          # this field is optional
          type: DirectoryOrCreate
