---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.wordpress_service_name}}
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: {{ .Values.wordpress.wordpress_service_type }}
