namespace: wordpressmariadb

Storage:
  storage_class_name: "kang-sc"

mariadb:
  #Each one of your pods will be identified by the following name {name}-0, {name}-1 ...
  mariadb_statefulset_name: "mariadb-sts"

  #Please choose the number of replicas for mariadb
  mariadb_replicas: 3

  #The name of the volume which will be storing the data of mariadb on
  mariadb_pvc_name: datadir

  #Name of the service
  mariadb_service_name: mariadb-service

  #Name of the configmap
  mariadb_configmap_name: mariadb-configmap

  #Name of the secret
  mariadb_secret_name: mariadb-secret


  mariadb_root_password:
  mariadb_mysql_user:
  mariadb_mysql_passowrd:

  #The image for mariadb
  mariadb_image: mariadb

  #The storage for mariadb
  mariadb_pvc_size: 20


  mariadb_master_user: repluser
  mariadb_master_password: replsecret

  #The number of times to retry to connect to the master by each slave
  mariadb_master_conn_retry: 3


maxscale:
  #The protocol which is going to be used to connect to servers
  #Available options are, MariaDBClient maxscaled and MariaDBBackend
  maxscale_server_protocol: MariaDBBackend

  #Choose the monitoring modules
  #The available options are, mariadbmon, clustrixmon, Columnstore
  maxscale_monitor_module: mariadbmon

  #Number of times to try to reconnect to a server before considering it down
  maxscale_fail_count: 3

  #To enable auto_failover set the value to 1. (0 would be for disabled)
  maxscale_auto_failover: 1


  maxscale_user: maxscale
  maxscale_password: maxscalepassword

  #The number of seconds(ms) for maxscale to check on servers
  maxscale_monitor_interval: 1000

  maxscale_router_protocol: MariaDBProtocol

  #Name of the deployment for maxscale
  maxscale_deployment_name: maxscale-deployment

  #Choose the number of replicas for Maxscale
  maxscale_replica_count: 1

  maxscale_configmap_name: maxscale-config
  maxscale_service_name: maxscale-service




wordpress:
  #Name of the ingres which is going to be used for the wordpress application
  wordpress_ingress_name: wordpress

  #The name of cluster certificate issue
  wordpress_cluster_issuer_name: prod-issuer

  #Add the class for ingress
  wordpress_ingress_class: nginx

  #Please add the domain name which you want to host your wordpress on
  wordpress_domain: wordpress.oblivionone.com

  #The tls secret name
  wordpress_ingress_secret_name: kang-ingress-secret
  #The path on which you want to host your website
  wordpress_domain_path: /

  #The name of wordpress SVC
  wordpress_service_name: wordpress

  #The name of nginx configmap
  wordpress_nginx_configmap_name: nginx-config

  #Wordpress secret name
  wordpress_secret_name: wordpress-secret

  #The name of wordpress statefulset
  wordpress_statefulset_name: wordpress

  #The image name of wordpress
  wordpress_images: wordpress:php8.2-fpm

  #The name of PVC
  wordpress_volume_name: wordpressdata

  #The size of PVC
  wordpress_volume_size: 10

  #The servie type of wordpress SVC
  wordpress_service_type: ClusterIP




