apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  {{- include "replicas" . | nindent 2  }}

  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        #adding variable
        image: {{ .Values.image_name }}
        # adding a chuck of code
        #adding "-" would render white spaces useless
                            {{- toYaml .Values.network | nindent 8  }}

