apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mariadb.mariadb_configmap_name }}
  namespace: {{ .Values.namespace }}

data:

  primary.cnf: |
    [mariadb]
    log-bin                         # enable binary logging
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)
    gtid_strict_mode
    log_slave_updates
  replica.cnf: |
    [mariadb]
    log-bin                         # enable binary logging
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)
    gtid_strict_mode
    log_slave_updates

  primary.sql: |
    CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
    GRANT REPLICATION REPLICA ON *.* TO 'repluser'@'%';
    CREATE DATABASE primary_db;

    CREATE USER 'maxscale'@'%' IDENTIFIED BY 'maxscalepassword';
    GRANT ALL ON *.* TO 'maxscale'@'%';
    CREATE DATABASE wordpress;
    CHANGE MASTER TO
    MASTER_HOST="{{ .Values.mariadb.mariadb_statefulset_name }}-1.{{ .Values.namespace }}.svc.cluster.local",
    MASTER_USER="{{ .Values.mariadb.mariadb_master_user }}",
    MASTER_PASSWORD= "{{ .Values.mariadb.mariadb_master_password }}",
    MASTER_CONNECT_RETRY= {{ .Values.mariadb.mariadb_master_conn_retry }};


  secondary.sql: |
    # We have to know name of sts (`mariadb-sts`) and
    # service `mariadb-service` in advance as an FQDN.
    # No need to use master_port
    CHANGE MASTER TO
    MASTER_HOST="{{ .Values.mariadb.mariadb_statefulset_name }}-0.{{ .Values.namespace }}.svc.cluster.local",
    MASTER_USER="{{ .Values.mariadb.mariadb_master_user }}",
    MASTER_PASSWORD="{{ .Values.mariadb.mariadb_master_password }}",
    MASTER_CONNECT_RETRY= {{ .Values.mariadb.mariadb_master_conn_retry }};


