apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.mariadb_service_name }}
  namespace: {{ .Values.mariadb.mariadb_namespace }}
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb-port
  clusterIP: None
  selector:
    app: mariadb
