apiVersion: v1
kind: ConfigMap
metadata:
  name: maxscale-config
  namespace: wordpressmariadb
data:
  maxscale.cnf: |
    [maxscale]
    threads=auto

    [server1]
    type=server
    address=mariadb-sts-0.mariadb-service.wordpressmariadb.svc.cluster.local
    port=3306
    protocol=MariaDBBackend 

    [server2]
    type=server
    address=mariadb-sts-1.mariadb-service.wordpressmariadb.svc.cluster.local
    port=3306
    protocol=MariaDBBackend

    [server3]
    type=server
    address=mariadb-sts-2.mariadb-service.wordpressmariadb.svc.cluster.local
    port=3306
    protocol=MariaDBBackend

    [MariaDB-Monitor]
    type=monitor
    module=mariadbmon
    servers=server1,server2,server3
    failcount=3
    auto_failover=1
    user=maxscale
    password=maxscalepassword
    monitor_interval=1000ms


    [RW-service]
    type=service
    router=readwritesplit
    servers=server1,server2,server3
    user=maxscale
    password=maxscalepassword
    
  
  
    [RW_listener]
    type=listener
    service=RW-service
    protocol=MariaDBProtocol
    port=3306
