---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.maxscale.maxscale_configmap_name }}
  namespace: {{ .Values.maxscale.maxscale_namespace }}

data:
  maxscale.cnf: |
    [maxscale]
    threads=auto

    [server1]
    type=server
    address="{{ .Values.mariadb.mariadb_statefulset_name }}-0.{{ .Values.mariadb.mariadb_namespace }}.svc.cluster.local"
    port=3306
    protocol=MariaDBBackend

    [server2]
    type=server
    address="{{ .Values.mariadb.mariadb_statefulset_name }}-1.{{ .Values.mariadb.mariadb_namespace }}.svc.cluster.local"
    port=3306
    protocol=MariaDBBackend

    [server3]
    type=server
    address="{{ .Values.mariadb.mariadb_statefulset_name }}-2.{{ .Values.mariadb.mariadb_namespace }}.svc.cluster.local"
    port=3306
    protocol={{ .Values.maxscale.maxscale_server_protocol }}

    [MariaDB-Monitor]
    type=monitor
    module={{ .Values.maxscale.maxscale_monitor_module }}
    servers=server1,server2,server3
    failcount={{ .Values.maxscale.maxscale_fail_count }}
    auto_failover={{ .Values.maxscale.maxscale_auto_failover}}
    user={{ .Values.maxscale.maxscale_user }}
    password={{ .Values.maxscale.maxscale_password }}
    monitor_interval={{ .Values.maxscale.maxscale_monitor_interval }}ms


    [RW-service]
    type=service
    router=readwritesplit
    servers=server1,server2,server3
    user={{ .Values.maxscale.maxscale_user }}
    password={{ .Values.maxscale.maxscale_password }}



    [RW_listener]
    type=listener
    service=RW-service
    protocol={{ .Values.maxscale.maxscale_router_protocol }}
    port=3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.maxscale.maxscale_deployment_name }}
 namespace:   {{ .Values.maxscale.maxscale_namespace }}

 labels:
   app: maxscale
spec:
 replicas: {{ .Values.maxscale.maxscale_replica_count }}
 selector:
   matchLabels:
     app: maxscale
 template:
   metadata:
     labels:
       app: maxscale
   spec:
     containers:
     - name: maxscale
       image: mariadb/maxscale
       ports:
       - containerPort: 3306
         name: maxscale-port
       volumeMounts:
       - name: maxscaleconfigmap
         mountPath: /etc/maxscale.cnf
         subPath: maxscale.cnf
     volumes:
     - name: maxscaleconfigmap
       configMap:
         name: {{ .Values.maxscale.maxscale_configmap_name }}


---

apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.maxscale.maxscale_service_name }}
 namespace: {{ .Values.maxscale.maxscale_namespace }}

spec:
 ports:
 - port: 3306
   name: maxscale-port
 selector:
   app: maxscale