apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.maxscale.maxscale_service_name }}
 namespace: {{ .Values.maxscale.maxscale_namespace }}

spec:
 ports:
 - port: 3306
   name: maxscale-port
 selector:
   app: maxscale