apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.wordpress.wordpress_secret_name }}
    namespace: wordpressmariadb
type: Opaque
data:
  # Encoded value: echo -n 'secret'|base64
  wordpress_db_password: d29yZHByZXNz #wordpress
  mysql_user: d29yZHByZXNz #wordpress
  mysql_password: d29yZHByZXNzcGFzc3dvcmQ= #wordpresspassword
